/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1869362b-d34e-44b4-9ad9-399d5a299bb0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EjgZJJPNS",
    "aws_user_pools_web_client_id": "6u8ro68aut77s4sthuor4gqhnl",
    "oauth": {}
};


export default awsmobile;
